### ISSUE TITLE
Advantages over pure RQ

### ISSUE THREAD

**Issue by moi90** [rq/Flask-RQ2#85]
I think the documentation would benefit from an explanation why we need Flask-RQ2 if we could use pure RQ as well. I have a hard time spotting the differences.

**Comment by levrik** [comment]
@moi90 Actually I couldn't get anything working with `Flask-RQ2` but with `rq` itself. Not sure what this package offers.

**Comment by devlounge** [comment]
yes, on python 3.7 I keeps getting errors with this, will go back to pure rq

**Comment by moi90** [comment]
Judging by the lack of communication by the authors, I consider this package to be dead.

**Comment by jezdez** [comment]
Hey @moi90, I would suggest to double-check your expectations when you open a ticket with a statement referring to your inability to weigh the pros and cons of a free (read: created in my unpaid, free time) software package.

I'm honestly just sad to see how you got from your original issue statement

> I think the documentation would benefit from an explanation why we need Flask-RQ2 if we could use pure RQ as well. I have a hard time spotting the differences.

to 

> Judging by the lack of communication by the authors, I consider this package to be dead.

And frankly until shown otherwise, I can only assume a bad faith attempt at guilt-tripping someone to provide additional free labor to make it easier for your to understand how the software works.

I would have loved if you would have written:

> I think the documentation would benefit from an explanation why we need Flask-RQ2 if we could use pure RQ as well. I have a hard time spotting the differences. **If you don't mind, I'll open a pull request with an update to the documentation once I've found out the differences.**

But you didn't, so it's mostly your loss.

**Comment by moi90** [comment]
> I can only assume a bad faith attempt at guilt-tripping someone to provide additional free labor to make it easier for your to understand how the software works.

No, not at all! I'm sorry if it came across this way. Rather, I was hoping for some directions that would have enabled me to understand the differences.

If I had understood the differences myself, I would have made some more specific suggestions of even opened a pull request to enhance the documentation.

My judgement is solely based on the fact that there was no reaction whatsoever for more than one year.
